/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoundaryRouteImport } from './routes/boundary'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as HealthRouteImport } from './routes/health'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as PacketIdRouteImport } from './routes/packet.$id'
import { Route as WaterIdRouteImport } from './routes/water.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoundaryRoute = BoundaryRouteImport.update({
  id: '/boundary',
  path: '/boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketIdRoute = PacketIdRouteImport.update({
  id: '/packet/$id',
  path: '/packet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterIdRoute = WaterIdRouteImport.update({
  id: '/water/$id',
  path: '/water/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/health': typeof HealthRoute
  '/pipeline': typeof PipelineRoute
  '/plan': typeof PlanRoute
  '/reading': typeof ReadingRoute
  '/watchlist': typeof WatchlistRoute
  '/packet/$id': typeof PacketIdRoute
  '/water/$id': typeof WaterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/health': typeof HealthRoute
  '/pipeline': typeof PipelineRoute
  '/plan': typeof PlanRoute
  '/reading': typeof ReadingRoute
  '/watchlist': typeof WatchlistRoute
  '/packet/$id': typeof PacketIdRoute
  '/water/$id': typeof WaterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/health': typeof HealthRoute
  '/pipeline': typeof PipelineRoute
  '/plan': typeof PlanRoute
  '/reading': typeof ReadingRoute
  '/watchlist': typeof WatchlistRoute
  '/packet/$id': typeof PacketIdRoute
  '/water/$id': typeof WaterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boundary'
    | '/compare'
    | '/explore'
    | '/health'
    | '/pipeline'
    | '/plan'
    | '/reading'
    | '/watchlist'
    | '/packet/$id'
    | '/water/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boundary'
    | '/compare'
    | '/explore'
    | '/health'
    | '/pipeline'
    | '/plan'
    | '/reading'
    | '/watchlist'
    | '/packet/$id'
    | '/water/$id'
  id:
    | '__root__'
    | '/'
    | '/boundary'
    | '/compare'
    | '/explore'
    | '/health'
    | '/pipeline'
    | '/plan'
    | '/reading'
    | '/watchlist'
    | '/packet/$id'
    | '/water/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoundaryRoute: typeof BoundaryRoute
  CompareRoute: typeof CompareRoute
  ExploreRoute: typeof ExploreRoute
  HealthRoute: typeof HealthRoute
  PipelineRoute: typeof PipelineRoute
  PlanRoute: typeof PlanRoute
  ReadingRoute: typeof ReadingRoute
  WatchlistRoute: typeof WatchlistRoute
  PacketIdRoute: typeof PacketIdRoute
  WaterIdRoute: typeof WaterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boundary': {
      id: '/boundary'
      path: '/boundary'
      fullPath: '/boundary'
      preLoaderRoute: typeof BoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packet/$id': {
      id: '/packet/$id'
      path: '/packet/$id'
      fullPath: '/packet/$id'
      preLoaderRoute: typeof PacketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water/$id': {
      id: '/water/$id'
      path: '/water/$id'
      fullPath: '/water/$id'
      preLoaderRoute: typeof WaterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoundaryRoute: BoundaryRoute,
  CompareRoute: CompareRoute,
  ExploreRoute: ExploreRoute,
  HealthRoute: HealthRoute,
  PipelineRoute: PipelineRoute,
  PlanRoute: PlanRoute,
  ReadingRoute: ReadingRoute,
  WatchlistRoute: WatchlistRoute,
  PacketIdRoute: PacketIdRoute,
  WaterIdRoute: WaterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
